drivers/gpu/drm/i915/display/i9xx_plane.c
drivers/gpu/drm/i915/display/intel_backlight.c
drivers/gpu/drm/i915/display/intel_cursor.c
drivers/gpu/drm/i915/display/intel_display.c
drivers/gpu/drm/i915/display/intel_display_types.h
drivers/gpu/drm/i915/display/intel_dp.c
drivers/gpu/drm/i915/display/intel_fb.c
drivers/gpu/drm/i915/display/intel_fbc.c
drivers/gpu/drm/i915/display/intel_lspcon.c
drivers/gpu/drm/i915/display/intel_opregion.c
drivers/gpu/drm/i915/display/intel_sprite.c
drivers/gpu/drm/i915/display/skl_universal_plane.c
drivers/gpu/drm/i915/gem/i915_gem_execbuffer.c
drivers/gpu/drm/i915/gem/i915_gem_shrinker.c
drivers/gpu/drm/i915/gt/intel_ggtt.c
drivers/gpu/drm/i915/gt/intel_gt.c
drivers/gpu/drm/i915/intel_pm.c

This is a very "dumb" fix, just by renaming the
functions and adding/removing includes so they
match the driver files in the 6.0.2 tree.
The driver seems to compile, but I cannot test
it yet as my laptop with the 12th gen GPU has
not arrived yet.

Module now can be compiled for kernel 6.0.2

---

dkms.conf

Fix AUR install issue mentioned in https://github.com/strongtz/i915-sriov-dkms/issues/18#issuecomment-1367105944 .

dkms: fix compatible issue with Arch PKGBUILD

---

PKGBUILD
drivers/gpu/drm/i915/intel_runtime_pm.c

LLVM16 (still in RC, required for kCFI) complains about the lack of definition for `intel_wakeref_tracker_remove` when making its way through `#if IS_ENABLED(CONFIG_DRM_I915_DEBUG_RUNTIME_PM)` section in `intel_runtime_pm.c`.
Mitigate the concern by gating the call with a check for `CONFIG_DRM_I915_TRACK_WAKEREF` (without which the entire call chain makes no sense anyway).
Update PKGBUILD to 6.1.11

Fix LLVM16 ThinLTO/kCFI Build

---

drivers/gpu/drm/i915/display/intel_cdclk.c

From https://www.spinics.net/lists/stable/msg627300.html Adapted for the dual occurrence of said typo in this branch.

Port drm/i915/adlp: Fix typo for reference clock

---

drivers/gpu/drm/i915/pxp/intel_pxp_huc.c

intel_pxp_tee_stream_message does not exist in 6.1, and compiling with RAP on GCC or with LTO+kCFI on LLVM results in an implicit declaration error (likely other configuraitons too, no clue how vanilla 6.1 users are faring).

6.2 gate for call to intel_pxp_tee_stream_message

---

drivers/gpu/drm/i915/gem/i915_gem_execbuffer.c
drivers/gpu/drm/i915/gt/intel_execlists_submission.c
drivers/gpu/drm/i915/intel_memory_region.c
include/trace/define_trace.h

Function `get_random_u32_below()` is [introduced](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v6.1.4&id=346ac4a116cbad784f95ef9a1ab195dbe19230b0) since linux-6.1.4 to replace `prandom_u32_max()`.

i915: fix compatibility with linux-6.1 lower then version 6.1.6

---

drivers/gpu/drm/i915/display/intel_dp_mst.c

1297278ce239 backported changes to drm_dp_remove_payload requiring updating the ifdefs wrapping how drm_dp_remove_payload is called.

Fix drm_dp_remove_payload for 6.1.24+

---

drivers/gpu/drm/i915/display/intel_dp_mst.c

Fix drm_dp_remove_payload for 6.2.0 ~ 6.2.4 Introduced by #61

i915 module: Fix drm_dp_remove_payload for 6.2.0 ~ 6.2.4 

---

drivers/gpu/drm/i915/gt/intel_workarounds.c

Test in linux-6.2.13-200.fc37.x86_64 in Fedora 37, may also fixed the same issue in Ubuntu(#66) and Fedora Host([62](https://github.com/strongtz/i915-sriov-dkms/issues/62#issuecomment-1522107605))

Fix NULL pointer dereference error in wa_list_apply

---

drivers/gpu/drm/i915/gt/intel_workarounds.c

Tested on PVE Host 6.2.9-1-pve 6.2.11-1-pve, Gentoo guest 6.1.19-gentoo, Fedora 37 guest 6.2.13-200.fc37.x86_64.

More fixed for NULL pointer dereference error in wa_list_apply

---

drivers/gpu/drm/i915/gt/gen8_ppgtt.c
drivers/gpu/drm/i915/gt/intel_ggtt.c
drivers/gpu/drm/i915/gt/intel_ggtt_gmch.c
drivers/gpu/drm/i915/gt/intel_gtt.h
drivers/gpu/drm/i915/gt/uc/intel_guc_slpc.c
include/linux/ioport.h

Grsecurity's RAP does not tolerate inconsistent call signatures resulting from dynamic dispatch used to differentiate the gen11/12 hardware from older equipment. Haven't tested on LLVM's kCFI since the relevant changes were introduced, but good chance that it will not abide these mismatches as well.
Implement explicitly-casting function shims to provide consistent signatures and inform the compiler of the type conversion without attempting to rely on inference/undefined behavior.
Implement several bug-fixes for misc compiler errors encountered during the 6.4 port.

CFI-Compatible Shims and Miscellaneous Fixes

---

README.md
drivers/gpu/drm/i915/display/intel_connector.c
drivers/gpu/drm/i915/display/intel_display_core.h
drivers/gpu/drm/i915/display/intel_display_debugfs.c
drivers/gpu/drm/i915/display/intel_dp_mst.c
drivers/gpu/drm/i915/display/intel_fbdev.c
drivers/gpu/drm/i915/display/intel_hdcp.c
drivers/gpu/drm/i915/gem/i915_gem_mman.c
drivers/gpu/drm/i915/gem/i915_gem_mman.h
drivers/gpu/drm/i915/gem/i915_gem_shmem.c
drivers/gpu/drm/i915/i915_gpu_error.c

Tested desktop workloads (video QSV decode/encode and 3D accel) on Ubuntu 22.04 host and Windows 11 guest.

Add support for Linux 6.5.3

---

drivers/gpu/drm/i915/display/intel_dp.c

Allows for compilation on kernel 6.2.16-18+ (fixes issues #117 & #121)

Update intel_dp.c (compile on kernel 6.2.16-18+)

---

drivers/gpu/drm/i915/display/intel_fbdev.c

As mentioned in  #123 
The makro
FB_GEN_DEFAULT_DEFERRED_IO_OPS
used in file ./drivers/gpu/drm/i915/display/intel_fbdev.c
has been renamed to
FB_GEN_DEFAULT_DEFERRED_IOMEM_OPS
This PR fixes that using the C if preprocessor to apply the fix if needed

fixing build for kernel >6.6

---

README.md

- Changes the `dkms -i` to `dkms install`
- Add `--force` argument to override the default behavior where the built module will NOT be reinstalled if there is an existing module with same name
Tesed on PVE kernel 6.5.13-3-pve

Update dkms install command in README.md

---

drivers/gpu/drm/i915/display/intel_dp_mst.c

**Prcoceeding with this merge may break builds in PVE with kernel < 6.5.13-5-pve**
Changed the signature of `drm_dp_calc_pbn_mode` to fix the install error on the PVE kernel `6.5.13-5-pve`
Applying this change can fix #151

Changed the signature of `drm_dp_calc_pbn_mode`

---

README.md

Installation readme had spelling error on initramfs possibly leading to issues on comprehension. Simply correcting the spelling for clarity.

Corrected Spelling on initramfs

---

drivers/gpu/drm/i915/display/intel_dp_mst.c

dkms.conf configuered exclusive_kernels as: BUILD_EXCLUSIVE_KERNEL="^(6\.[1-5]\.)"
However code here is only for kernel >=6.6.14.
This change fix bugs when building on kernels of lower versions such as 6.5.11

fix bug on kernels < 6.6.14

---

drivers/gpu/drm/i915/display/intel_backlight.c
drivers/gpu/drm/i915/display/intel_backlight.h

On kernels >v6.6.32 builds fail because `pwm_apply_state()` got renamed to `pwm_apply_might_sleep()` in
`linux/pwm.h`. This does not (yet?) apply to v6.7 but it is the case in v6.8 and onwards.
This creates a macro for the correct function depending on the version and currently builds on linux-lts again.

Fix build for linux-lts (6.6.34)

---

drivers/gpu/drm/i915/display/intel_dp.c

Since LTS Kernel 6.1 is at version: 6.1.103 this small patch is needed so that the module is able to compile properly.

Fix for Kernel 6.1.x

---

drivers/gpu/drm/i915/i915_ttm_buddy_manager.c

This fix has successfully built and created VFs in the following environments:
OS: Arch Linux
Linux Kernel: 6.10.10-arch1-1
CPU: Intel(R) N100

Fix "too few arguments to function 'drm_buddy_free_list'" error on Linux 6.10.x

---

drivers/gpu/drm/i915/gem/i915_gem_shmem.c

Porting the missing section on [0b62af2](https://github.com/gregkh/linux/commit/0b62af28f249b9c4036a05acfb053058dc02e2e2)
May fix: #137
May fix: #175

fix possible memory leak at 6.5+

---

README.md

Updated various sections of README.md, verified the steps myself with a clean install of PVE 8.3/Kernel 6.8 and Ubuntu 24.04.1 LTS Guest VM.

Updated README.md to reflect new Linux Guest installations (Ubuntu 24.04 LTS/Kernel 6.8)

---

README.md

Verified the firmware extraction method in #225 myself and it worked. In theory the updated guide would ensure compatibility across all future Windows driver versions.

Updated Instructions for Windows VM Usage

---

PKGBUILD
README.md
i915-modprobe.conf
i915-sriov-dkms.install

The kernel command line in `README.md`
```
i915.enable_guc=3 i915.max_vfs=7 module_blacklist=xe
```
could be translated into a `modprobe` configuration file:
```
blacklist xe
options i915 enable_guc=3
options i915 max_vfs=7
```
This patch creates such file and including it with Arch Linux `PKGBUILD`.

Arch Linux package: include necessary modprobe configuration
